version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: runBuild
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud