version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            sudo npm install -g
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud